# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71c5427c71ce07a548f5807d9f7ec50086a4a58b2023e5da0b6e1c4843673423a9798172071603b0df4537e22b5c6b0cc48d39659b7aa687c0b40abd575ea34e

test:
  secret_key_base: 5096d7c46c273ff9e9d0677a66404c9aba68d073596e42de728c883af925bd8481993dab086a4fb5d7fa951959cfe41f6c48afe496d594553531061b18b49b57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
